# Site settings
title: KaunasPHP.lt - Kauno PHP bendruomenė
email: your-email@domain.com
description: Kaunas PHP bendruomenė
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kaunasphp.lt" # the base hostname & protocol for your site
twitter_username: kaunasphp
github_username:  kaunasphp

# Build settings
markdown: kramdown
include: ["media", "scripts", "styles"]
